build.gradle.kts
src/main/kotlin/org/openrewrite/MarkdownRecipeArtifact.kt
src/main/kotlin/org/openrewrite/MarkdownRecipeDescriptor.kt
src/main/kotlin/org/openrewrite/RecipeMarkdownGenerator.kt
src/main/kotlin/org/openrewrite/RecipeOption.kt
src/main/resources/recipeDescriptors.yml

So that we can see what changes between releases.

Adds ability to generate serialized recipes

---

src/main/kotlin/org/openrewrite/MarkdownRecipeDescriptor.kt
src/main/kotlin/org/openrewrite/RecipeMarkdownGenerator.kt
src/main/resources/recipeDescriptors.yml

When we're making a changelog, having that information would be nice. 
Note that this is with the previous version of rewrite so that we can then run the comparison against the latest and get the descriptions as well.

Add a description for all of the recipes

---

src/main/kotlin/org/openrewrite/MarkdownRecipeDescriptor.kt
src/main/kotlin/org/openrewrite/RecipeMarkdownGenerator.kt
src/main/resources/recipeDescriptors.yml

When we're making a changelog, having that information would be nice.

Add a doc link for each recipe

---

src/main/kotlin/org/openrewrite/RecipeMarkdownGenerator.kt
src/main/resources/CHANGELOG-2022-11-23.md

Also make some minor fixes in the generator.

Add CHANGELOG for 7.32.0 release vs. now

---

README.md
build.gradle.kts
src/main/kotlin/org/openrewrite/RecipeMarkdownGenerator.kt
src/main/resources/snapshot-CHANGELOG-2022-11-30.md
src/main/resources/snapshotRecipeDescriptors.yml

* Allows the user to specify a type of deploy (release or snapshot) that will create a CHANGELOG for the respective type.
* Updates the README with a bunch of useful information that was missing
* Adds a snapshot file for tracking changes over snapshots

Add the ability to generate changelogs for snapshots

---

src/main/kotlin/org/openrewrite/RecipeMarkdownGenerator.kt

You can see what this looks like in a recipe I manually copied over here: https://docs.openrewrite.org/reference/recipes/circleci/installorb

Add a link to the Moderne SaaS in each recipe

---

suppressions.xml

This suppression is for https://github.com/moderneinc/dependency-vulnerability-reports/issues/491

chore: Update suppressions

---

.github/workflows/pages.yml
src/main/kotlin/org/openrewrite/RecipeMarkdownGenerator.kt
src/main/resources/recipeDescriptors.yml

Toying around; think we might be able to provide a preview for other changes using something like this.
Might be best if we tie in one more action to convert the markdown to HTML before we upload.

Create pages.yml to pushing Markdown to GitHub Pages

---

.github/workflows/pages.yml
build.gradle.kts
src/main/resources/recipeDescriptors.yml

https://openrewrite.github.io/rewrite-recipe-markdown-generator/

Convert all markdowns

---

src/main/kotlin/org/openrewrite/RecipeMarkdownGenerator.kt

Suppress Maven/Gradle snippets for Gradle/Maven recipes

---

src/main/kotlin/org/openrewrite/RecipeMarkdownGenerator.kt

Fixes: https://github.com/openrewrite/rewrite-recipe-markdown-generator/issues/57
Here's an example of what a recipe doc with data tables looks like:
**org.openrewrite.java.dependencies.DependencyVulnerabilityCheck**
_This is a software composition analysis (SCA) tool which detects publicly disclosed vulnerabilities. If vulnerabilities are found, it will generate a report linking to the associated CVE entries. Vulnerability information comes from the [GitHub Security Advisory Database](https://docs.github.com/en/code-security/security-advisories/global-security-advisories/about-the-github-advisory-database), which aggregates vulnerability data from several public databases, including the [National Vulnerability Database](https://nvd.nist.gov/) maintained by the United States government. …

Add data tables to auto-generated docs

---

src/main/kotlin/org/openrewrite/RecipeMarkdownGenerator.kt

Fix contributor email links

---

build.gradle.kts

For https://github.com/openrewrite/rewrite-okhttp/issues/1
Fixes https://github.com/openrewrite/rewrite-okhttp/issues/4

Add rewrite-okhttp

---

suppressions.xml

Remove outdated suppressions.xml and delay jackson-databind

Remove outdated suppressions.xml and delay jackson-databind

---

src/main/kotlin/org/openrewrite/RecipeMarkdownGenerator.kt
src/main/kotlin/org/openrewrite/RecipeOrigin.kt

Contributors as paragraph & fix link to Refaster recipes

---

suppressions.xml

Match suppression date of spring-boot.

Bump jackson-databind date in suppressions.xml

---

build.gradle.kts

rewrite-third-party still needs some validation before a release, but other than that I think we could add all of these.

Document additional libraries

---

settings.gradle.kts

Use this link to re-run the recipe: https://app.moderne.io/recipes/builder/Zb7BQc324?organizationId=NTUyM2Y5NWYtN2RjMC00Y2FiLWJmMmYtMmY2MmMzNjU1OWQz

refactor: Upgrade Develocity

---

src/main/kotlin/org/openrewrite/RecipeMarkdownGenerator.kt

Move data tables below usage, given the added height

---

src/main/kotlin/org/openrewrite/RecipeMarkdownGenerator.kt

Quick change to also print the recipe installation instructions, such that folks have an easy way to install the latest version as needed.

Generate CLI recipe installation instructions

---

src/main/kotlin/org/openrewrite/RecipeMarkdownGenerator.kt

Another small usability improvement for folks unable to run `mod config recipes moderne sync` just yet.

Show command to install all recipes into the CLI

---

src/main/kotlin/org/openrewrite/RecipeMarkdownGenerator.kt

This PR fixes a broken link to Moderne CLI.

Fix broken link to Moderne CLI

---

src/main/kotlin/org/openrewrite/Licenses.kt
src/main/kotlin/org/openrewrite/RecipeMarkdownGenerator.kt

Selectively show parts of the docs based on license

---

src/main/kotlin/org/openrewrite/RecipeMarkdownGenerator.kt

- Fixes: https://github.com/openrewrite/rewrite-recipe-markdown-generator/issues/147
- Fixes: https://github.com/openrewrite/rewrite-recipe-markdown-generator/issues/146

Adjust recipe details based on license

---

src/main/kotlin/org/openrewrite/RecipeMarkdownGenerator.kt
src/main/resources/8-42-0-Release.md

- Fixes: https://github.com/openrewrite/rewrite-recipe-markdown-generator/issues/150

Add total recipe count to changelog gen

---

build.gradle.kts
src/main/kotlin/org/openrewrite/Licenses.kt

- Attempts to fix: https://github.com/openrewrite/rewrite-recipe-markdown-generator/issues/154

Handle Moderne licenses better

---

src/main/kotlin/org/openrewrite/RecipeMarkdownGenerator.kt

As mentioned in an internal doc, this option is planned but not yet released.

Install jars in parallel, once supported in CLI

---

src/main/kotlin/org/openrewrite/ChangedRecipe.kt
src/main/kotlin/org/openrewrite/MarkdownRecipeArtifact.kt
src/main/kotlin/org/openrewrite/MarkdownRecipeDescriptor.kt

Use this link to re-run the recipe: https://app.moderne.io/recipes/org.openrewrite.staticanalysis.CommonStaticAnalysis?organizationId=T3BlblJld3JpdGU%3D

refactor: Common static analysis issues

---

build.gradle.kts
src/main/kotlin/org/openrewrite/Licenses.kt

Add new rewrite-rewrite module

---

src/main/kotlin/org/openrewrite/RecipeDescriptorExtensions.kt

Wrap asterisks in the generated recipe yaml lists. 
Fixes #165

Wrap asterisk in quotes in recipe list options

---

src/main/kotlin/org/openrewrite/RecipeMarkdownGenerator.kt
src/main/kotlin/org/openrewrite/RecipeOrigin.kt
src/main/resources/8-45-0-Release.md

Now that there's rewrite-spring and rewrite-hibernate under two separate groupIds we want to avoid clashes.

Include groupId with version placeholder

---

build.gradle.kts
src/main/resources/8-47-1-Release.md
src/main/resources/recipeDescriptors.yml

- https://github.com/openrewrite/rewrite-docs/pull/354

Openrewrite v8.47.1

---

build.gradle.kts

related to: https://github.com/moderneinc/dependency-vulnerability-reports/issues/820

chore: update org.owasp.dependencycheck to latest.release

---

build.gradle.kts
src/main/kotlin/org/openrewrite/RecipeMarkdownGenerator.kt

Generate GraphQL query to install latest versions to Moderne

---

src/main/kotlin/org/openrewrite/RecipeMarkdownGenerator.kt

No longer used now that we have an option to write latest versions only

Drop the option to run without recipe sources passed in

---

src/main/resources/8-52-0-Release.md
src/main/resources/recipeDescriptors.yml

OpenRewrite v8.52.0

---

build.gradle.kts
src/main/kotlin/org/openrewrite/RecipeMarkdownGenerator.kt

Ensures we're able generate the docs a lot faster.

Load recipe jars in parallel

---

src/main/kotlin/org/openrewrite/RecipeMarkdownGenerator.kt

- Follows on from https://github.com/openrewrite/rewrite-recipe-markdown-generator/commit/a16f708eabaa75de03af637a4a767b6d3eed3945

Replace `recipePath` with `getRecipePath` in lists of recipes

---

build.gradle.kts
src/main/resources/8-62-0-Release.md
src/main/resources/recipeDescriptors.yml

openrewrite-v8.62.0

---

build.gradle.kts

Add environment variable support for analyzers
