build.gradle.kts, suppressions.xml
https://github.com/openrewrite/rewrite-recipe-markdown-generator/actions/runs/1728635566
False-positive identification of rewrite-jhipster being an incorrect or otherwise outdated jhipster dependency.
=> dependency-check false positive identifier on jhipster

src/main/kotlin/org/openrewrite/RecipeMarkdownGenerator.kt
Adds a separate tab to each recipe page with a quick Maven shell command.
For a sample recipe: https://docs.openrewrite.org/reference/recipes/java/testing/junit5/junit5bestpractices
It generates an additional tab:
```
{% tab title="Maven Command Line" %}
{% code title="shell" %}
\```shell
mvn org.openrewrite.maven:rewrite-maven-plugin:4.32.0:run \
-Drewrite.recipeArtifactCoordinates=org.openrewrite.recipe:rewrite-testing-frameworks:1.26.1 \
-DactiveRecipes=org.openrewrite.java.testing.junit5.JUnit5BestPractices
\```
{% endcode %}
{% endtab %}
```
That allows users to quickly apply a recipe to Maven projects without having to copy and paste the pom.xml snippet into the right place. Would be helpful, without being too distracting I recon.
=> Add separate tab to generate a Maven shell command for rapid execution

src/main/kotlin/org/openrewrite/RecipeMarkdownGenerator.kt
I'm guessing this is what was intended, as now it renders the asterisks instead of applying the styling, as shown on for example: https://docs.openrewrite.org/reference/recipes/java/cleanup/methodparampad
=> Show recipe name in bold & italics

src/main/kotlin/org/openrewrite/ChangedRecipe.kt, src/main/kotlin/org/openrewrite/MarkdownRecipeArtifact.kt, src/main/kotlin/org/openrewrite/RecipeMarkdownGenerator.kt, src/main/resources/recipeDescriptors.yml
* Adds a new ChangedRecipe class which contains all the information about a recipe needed for the CHANGELOG
* Updates the MarkdownRecipeArtifact class to have a map of recipe names to descriptors to assist in detection of changes
* Updates the RecipeMarkdownGenerator class to build the CHANGELOG when run
* Updates the recipeDescriptors to have the latest information with the latest style so this can work next time
* An example of what this CHANGELOG would look like can be found here: https://gist.github.com/mike-solomon/16727159ec86ee0f0406ba389cbaecb1
=> Create a CHANGELOG when building new recipes

src/main/kotlin/org/openrewrite/RecipeMarkdownGenerator.kt
Right now, the generator ignores all recipes that don't have a language category such as "Delete files" or "Find instances of type Quark". This means that all auto-generated documentation for these recipes don't work on our docs page. Let's add a "core" section to put all of these recipes in.
This fixes: https://github.com/openrewrite/rewrite-recipe-markdown-generator/issues/32
=> Fix empty general section

src/main/kotlin/org/openrewrite/RecipeMarkdownGenerator.kt
Fixes https://github.com/openrewrite/rewrite-docs/issues/120
Has a slight potential to make it harder to debug when a user reports a bug in say january, and we don't immediately know what version they used. But the versions will still be in the logs, and the convenience might out weigh the negative.
=> Use versionless Maven commands

src/main/kotlin/org/openrewrite/RecipeMarkdownGenerator.kt
Here's an example of what this would look like on a snapshot changelog: https://docs.openrewrite.org/changelog/snapshot-2023-01-30
=> Add link to snapshot guide in snapshot changelogs

src/main/kotlin/org/openrewrite/RecipeMarkdownGenerator.kt, src/main/kotlin/org/openrewrite/RecipeOrigin.kt
Previously, we linked to the top-level Git repository from recipes. Now, we should link directly to the file that contains the recipe.
This handles both imperative and declarative recipes as well as recipes from nested folders in rewrite.
=> Add direct links to recipes

src/main/kotlin/org/openrewrite/RecipeMarkdownGenerator.kt
* Removes a line talking about activating a recipe directly from the command line that doesn't appear to be relevant anymore.
* Clarifies you need to install Maven for the command to work
* Removes a sentence saying you need to add a dependency when you don't.
=> Fix incorrect information about running recipes

build.gradle.kts, src/main/kotlin/org/openrewrite/RecipeMarkdownGenerator.kt, src/main/resources/recipeDescriptors.yml
Fixes #47 
The thinking here is it's better to show any module in the build.gradle.kts, even as a commented out line, rather than have them be absent and wonder why.
=> Additional modules

src/main/kotlin/org/openrewrite/RecipeMarkdownGenerator.kt
Fixes: https://github.com/openrewrite/rewrite-docs/issues/139
@sambsnyd @timtebeek Would people know what a `Composite` recipe means? Should I perhaps use a different word or address this in a different way?
Here's what the `JUnit` page looks like with this change:
_Best practices for JUnit Jupiter tests._
_Recipes that include further recipes, often including the individual recipes below._
* [Clean Up Assertions](./cleanupassertions.md)
* [JUnit Jupiter best practices](./junit5bestpractices.md)
* [JUnit Jupiter migration from JUnit 4.x](./junit4to5migration.md)
* [OkHttp 3.x `MockWebServer` `@Rule` To 4.x `MockWebServer`](./updatemockwebserver.md)
* [Statically import JUnit Jupiter assertions](./staticimports.md)
* [Use `Assertions#assume*(..)` and Hamcrest's …
=> Specify that a recipe is a composite recipe

build.gradle.kts
jackson-bom.version 2.15.0 -> 2.15.2
Vulnerability report.
https://github.com/FasterXML/jackson/wiki/Jackson-Release-2.15.1 https://github.com/FasterXML/jackson/wiki/Jackson-Release-2.15.2 https://github.com/FasterXML/jackson/wiki/Jackson-Release-2.15.3 (withheld, as BOM missing)
=> Jackson BOM version 2.14.2 -> 2.15.2

build.gradle.kts
Added `org.openrewrite.recipe:rewrite-jenkins` to the `recipe` configuration
Part of the adoption checklist in openrewrite/rewrite-jenkins#4
@timtebeek 
No, but open to any suggestions
=> Include rewrite-jenkins

src/main/kotlin/org/openrewrite/RecipeMarkdownGenerator.kt, src/main/resources/recipeDescriptors.yml
So that people can be aware of the fact that the Moderne CLi exists and can be used to run recipes.
=> Add Moderne CLI to recipes

src/main/kotlin/org/openrewrite/RecipeMarkdownGenerator.kt
As seen on: https://docs.openrewrite.org/recipes/java/migrate/usetabsorspaces
That `null` is rather awkward; `false` is likely a better option for required configuration parameters.
=> Use false for boolean values; not null

src/main/kotlin/org/openrewrite/RecipeMarkdownGenerator.kt
Now users need to replace that path whereas `.` would work both for individual projects, as well as a folder containing multiple repositories.
We could also add a hint or tip right above or below that the CLI can run against multiple projects. It's likely to be spotted in the docs for folks new to OpenRewrite, and yet another nudge to try it out.
We can even make the Mod CLI tab the first one, as that would work for both users of Maven and Gradle. 🤔
=> Replace `<PATH>` with `.` to make it copy paste safe

build.gradle.kts, src/main/kotlin/org/openrewrite/RecipeOrigin.kt
Include LaunchDarkly after the v0.0.2 release:
https://github.com/openrewrite/rewrite-launchdarkly/releases
Draft until then, but a placeholder not to forget.
We now have a core few recipes to upgrade the library, search for feature keys & phase out boolean toggles.
=> Include LaunchDarkly recipes in the generated documentation

build.gradle.kts, src/main/kotlin/org/openrewrite/RecipeMarkdownGenerator.kt, src/main/kotlin/org/openrewrite/RecipeOption.kt
Add a fourth options column with example values, as indicated on the option annotations.
Helps users see what type of input is expected.
We could add the same value to the description instead of a fourth column, as it might be missing frequently.
Reported through OSS Slack: 
https://rewriteoss.slack.com/archives/C01A843MWG5/p1702462745389259
=> Show recipe option example values in table

src/main/kotlin/org/openrewrite/RecipeMarkdownGenerator.kt
Using `<pre>` for multiline examples + escaping tags inside the example value (e.g. for XML examples).
With the proposed changes it looks like this ([createxmlfile.md](https://github.com/openrewrite/rewrite-docs/blob/master/reference/recipes/xml/createxmlfile.md)):
_Note: There is a `\n` missing in [CreateXmlFile.java](https://github.com/openrewrite/rewrite/blob/e32535eeccc97f2ac33af74257accbe13888334c/rewrite-xml/src/main/java/org/openrewrite/xml/CreateXmlFile.java#L49-L50)_
For option examples that are multiline the table cell formatting is broken, see [mergeyaml.md](https://github.com/openrewrite/rewrite-docs/blob/master/reference/recipes/yaml/mergeyaml.md), [createxmlfile.md](https://github.com/openrewrite/rewrite-docs/blob/master/reference/recipes/xml/createxmlfile.md), …
=> Fix formatting for multiline examples

src/main/kotlin/org/openrewrite/RecipeMarkdownGenerator.kt
A lot of our static analysis recipes link to an external specification. We can provide additional context by converting those into a link.
For example:
- https://docs.openrewrite.org/recipes/java/logging/parameterizedlogging
- https://sonarsource.github.io/rspec/#/rspec/S2629
- https://sonarsource.github.io/rspec/#/rspec/S3457
=> RSPEC tag links for context when browsing recipes

src/main/kotlin/org/openrewrite/RecipeMarkdownGenerator.kt
These are used to run the recipe, or export the named data table with the CLI.
It's then convenient to have those names listed, as opposed to one a different page.
=> Include datatable name on recipe page

build.gradle.kts
These were previously excluded, but now that both the Maven and Gradle plugins support data tables, and we have a page to document recipes with data tables, it might be best to show these recipes now such that folks can find them more easily.
=> Document rewrite-all recipes now that we have data tables

src/main/kotlin/org/openrewrite/RecipeMarkdownGenerator.kt
Such that a copy-paste button is rendered for easier access.
Right now we see
After this change I hope the command is also rendered in a block with a copy paste button top right.
=> Show --init-script command in shell block

build.gradle.kts, src/main/kotlin/org/openrewrite/RecipeMarkdownGenerator.kt
Continuing a trend of automating more and more of the docs generation.
=> Generate correct changelog header & filename & link

src/main/kotlin/org/openrewrite/RecipeMarkdownGenerator.kt
- Fixes https://github.com/openrewrite/rewrite-spring/issues/618
I think this ought to work for both; even if pending this issue we don't yet change the build.gradle.kts files:
- https://github.com/openrewrite/rewrite/issues/3291
=> Adopt `setExportDatatables(true)` for Gradle to support .kts too

src/main/kotlin/org/openrewrite/RecipeMarkdownGenerator.kt
This follows on from a change just before where we generate a latest-versions.js: https://github.com/openrewrite/rewrite-recipe-markdown-generator/commit/26517361c37f2ff6e503b83fe8ecb30993147d03
Which is already used in rewrite-docs to render these placeholders for guides: https://github.com/openrewrite/rewrite-docs/commit/831f7729ab352fc0cc05674c3d7ef93569621c4f
Change the generator to produce recipe pages with version placeholders, instead of explicit versions.
Reduce the diff whenever we release a new version, to make it a change manageable in a review, as opposed to 3K files changed.
Are there further simplifications we can do now?
=> Generate recipe pages with version placeholders

src/main/kotlin/org/openrewrite/RecipeMarkdownGenerator.kt
To handle cases where special characters are wrapped in backticks.
- Fixes: https://github.com/openrewrite/rewrite-recipe-markdown-generator/issues/158
=> Improve recipe descriptions

src/main/kotlin/org/openrewrite/Licenses.kt, src/main/kotlin/org/openrewrite/RecipeMarkdownGenerator.kt
There were '/' to much in the URIs to match the licenses at read. Know we use the correct one and therefore the textual representation is aligned.
Align docs with definitions
=> fix license URI and description to meet textual requirements better

src/main/kotlin/org/openrewrite/RecipeMarkdownGenerator.kt
Trim the page lengths now that we're bringing back examples, as the data tables added a great deal of height to the page already.
=> Show data tables in tabs, and examples before usage

src/main/kotlin/org/openrewrite/RecipeMarkdownGenerator.kt
The documentation shows
```groovy
plugins {
id("org.openrewrite.rewrite") version("latest.release")
}
```
instead of
```groovy
plugins {
id("org.openrewrite.rewrite") version("7.8.0")
}
```
=> Change hardcoded version of Gradle's rewrite plugin to "latest.release"

src/main/kotlin/org/openrewrite/RecipeMarkdownGenerator.kt
Copied code from elsewhere in this file for use in the RecipesWithDataTables section to remove URLs from recipe name so it can be displayed correctly in the markdown
=> Use formattedDisplayName in RecipesWithDataTables section as in other sections

src/main/kotlin/org/openrewrite/RecipeMarkdownGenerator.kt
=> Include which recipes include other recipes

build.gradle.kts, src/main/kotlin/org/openrewrite/CliVersion.kt, src/main/kotlin/org/openrewrite/RecipeMarkdownGenerator.kt
The code for obtaining the CLI version is largely a duplicate of the SaaS code - just converted from Java to Kotlin - with a different HTTP library.
=> Add CLI version to the OR changelogs

src/main/kotlin/org/openrewrite/RecipeMarkdownWriter.kt
We had some concerns reported to us that not every contributor has signed up to be listed here, so to avoid issues we're for now removing their names here. The metadata is retained, and we continue to appreciate the work done previously and going forward!
=> Drop contributors from individual recipe pages

src/main/kotlin/org/openrewrite/RecipeMarkdownGenerator.kt, src/test/kotlin/org/openrewrite/RecipeMarkdownGeneratorTest.kt
- Replace hardcoded if statements with generic regex pattern matcher
- Support any Spring Boot major/minor version combinations (3.x, 4.x...)
- Maintain separate moderne-edition and community-edition path handling
- Add comprehensive tests covering current and future Spring Boot versions
=> Refactor Spring Boot upgrade recipe path generation to be future-proof
